@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.lirelent.guidebook.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;