@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lirelent_gigaherz.guidebook.guidebook.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;