@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.lirelent.guidebook.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;