@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lirelent_gigaherz.guidebook.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;