@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lirelent_gigaherz.guidebook.guidebook;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;