@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.lirelent.guidebook.server;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;