@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lirelent_gigaherz.guidebook.server;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;